// Cloudflare Worker entrypoint.
//
// Astro 6 + @astrojs/cloudflare v13 delegates fetch handling to the
// adapter's `handle()`. We own this file only so we can:
//   - Wire `ctx.waitUntil` into `lib/background.ts` synchronously at
//     request entry, so the FIRST post-response background task in a
//     fresh isolate is registered without racing a dynamic import.
//   - Add a custom `scheduled()` handler for the nightly GitHub backup
//     cron with structured observability.
//
// `env` and `ctx` are typed against `Env` (auto-generated by
// `wrangler types` into the gitignored worker-configuration.d.ts) and
// the standard ExecutionContext. The fetch handler just forwards both
// to the adapter; bindings are accessed inside services via
// `import { env } from "cloudflare:workers"` or
// `apps/web/src/lib/runtime.ts:getRuntimeBindings()`.

import { handle } from "@astrojs/cloudflare/handler";
import { runWithWaitUntil, setCloudflareWaitUntil } from "./lib/background";
import { runDueGitHubBackupSyncs } from "./lib/github-backup";
import { runSearchReconciler } from "./lib/search-reconciler";
import { buildServiceContext } from "./lib/service-context";

type WaitUntilCtx = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch(request: Request, env: unknown, ctx: WaitUntilCtx) {
    // Thread the runtime's ctx.waitUntil through AsyncLocalStorage so
    // background tasks scheduled during this request register against
    // THIS request's ctx. Cloudflare serves multiple concurrent
    // requests per isolate; the previous module-level global racey'd
    // them. (Audit cycle 5 finding.)
    return runWithWaitUntil(
      (promise) => ctx.waitUntil(promise),
      () => handle(request, env, ctx),
    );
  },
  scheduled(controller: unknown, _env: unknown, ctx: WaitUntilCtx) {
    const startedAt = Date.now();
    const cronExpr =
      (controller as { cron?: string } | null)?.cron ?? "(unknown)";
    setCloudflareWaitUntil((promise) => ctx.waitUntil(promise));

    // Two crons share this handler — dispatch by expression so the
    // reconciler at 03:30 UTC doesn't run the GitHub backup at 03:00.
    if (cronExpr === "30 3 * * *") {
      ctx.waitUntil(
        runSearchReconciler()
          .then((result) => {
            console.log(
              JSON.stringify({
                event: "vpg.cron.completed",
                job: "search-reconciler",
                cron: cronExpr,
                duration_ms: Date.now() - startedAt,
                workspaces: result.workspaces,
                pages: result.pages,
                folders: result.folders,
                comments: result.comments,
              }),
            );
          })
          .catch((error) => {
            console.error(
              JSON.stringify({
                event: "vpg.cron.failed",
                job: "search-reconciler",
                cron: cronExpr,
                duration_ms: Date.now() - startedAt,
                error: error instanceof Error ? error.message : String(error),
              }),
            );
          }),
      );
      return;
    }

    ctx.waitUntil(
      (async () => {
        // Cron runs as the system (no cookies / no actor). Build a
        // privileged service context the same way the search
        // reconciler does.
        const seedCookies = { get: () => undefined } as never;
        const { ctx: serviceCtx } = await buildServiceContext({
          cookies: seedCookies,
        });
        return runDueGitHubBackupSyncs(serviceCtx);
      })()
        .then((result) => {
          console.log(
            JSON.stringify({
              event: "vpg.cron.completed",
              job: "github-backup",
              cron: cronExpr,
              duration_ms: Date.now() - startedAt,
              synced: result?.synced ?? 0,
              failed: result?.failed ?? 0,
            }),
          );
        })
        .catch((error) => {
          console.error(
            JSON.stringify({
              event: "vpg.cron.failed",
              job: "github-backup",
              cron: cronExpr,
              duration_ms: Date.now() - startedAt,
              error: error instanceof Error ? error.message : String(error),
            }),
          );
        }),
    );
  },
};
